repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
  - id: check-ast
- repo: https://github.com/hadialqattan/pycln
  rev: v1.3.3
  hooks:
    - id: pycln
- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
    - id: isort
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
